/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hyperbeast.form;

import com.hyperbeast.entity.KhachHang;
import com.hyperbeast.model.khachHangModel;
import com.hyperbeast.utils.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class khachHangJDialog extends javax.swing.JDialog {

    /**
     * Creates new form khachHangJDialog
     */
    int pageNumber;
    int page = 1;
    int pageSelect;
    khachHangModel kHModel = new khachHangModel();
    ArrayList<KhachHang> listKH;
    public khachHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        trangThaiCB.setSelectedIndex(0);
        listKH = kHModel.getKhachHang();
        getPage();
        statusPage();
        loadData(pageSelect);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        khachHangTbl = new javax.swing.JTable();
        tenKHTxt = new com.hyperbeast.swing.TextField();
        sdtKHTxt = new com.hyperbeast.swing.TextField();
        ngayTaoTxt = new com.hyperbeast.swing.TextField();
        trangThaiCB = new com.hyperbeast.swing.Combobox();
        jButton1 = new javax.swing.JButton();
        themBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khách Hàng");

        khachHangTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách hàng", "Tên khách hàng", "Số điện thoại", "Ngày Tạo", "Trạng thái"
            }
        ));
        khachHangTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(khachHangTbl);

        tenKHTxt.setLabelText("Tên Khách Hàng");

        sdtKHTxt.setLabelText("Số điện thoại");

        ngayTaoTxt.setEnabled(false);
        ngayTaoTxt.setLabelText("Ngày tạo");

        trangThaiCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hoạt động", "Không hoạt động" }));
        trangThaiCB.setSelectedIndex(-1);
        trangThaiCB.setLabeText("Trạng thái");

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        themBtn.setBackground(new java.awt.Color(0, 102, 255));
        themBtn.setForeground(new java.awt.Color(255, 255, 255));
        themBtn.setText("Thêm");
        themBtn.setEnabled(false);
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        pageLbl.setText("Trang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jButton5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tenKHTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sdtKHTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ngayTaoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trangThaiCB, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(themBtn)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pageLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sdtKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ngayTaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(trangThaiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(themBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(page <= pageNumber) {
            if(page == 1) {
                return;
            }
            page--;
            getPage();
            statusPage();
            loadData(pageSelect);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(page >= 1 && page < pageNumber) {
            page++;
            getPage();
            statusPage();
            loadData(pageSelect);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void khachHangTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangTblMouseClicked
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_khachHangTblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        // TODO add your handling code here:
        validateKH(1);
    }//GEN-LAST:event_themBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = khachHangTbl.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn dòng cập nhật");
            return;
        }
        validateKH(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    void statusPage() {
        listKH = kHModel.getKhachHang();
        pageNumber = (int) Math.ceil((listKH.size()/5.0));
        pageLbl.setText(page + "/" + pageNumber);
    }
    
    void getPage() {
        pageSelect = (page - 1) * 5;
    }
    
    void getData() {
        int selectedRow = khachHangTbl.getSelectedRow();
        if(selectedRow < 0) {
            return;
        }
        themBtn.setEnabled(false);
        tenKHTxt.setText(khachHangTbl.getValueAt(selectedRow, 1) + "");
        sdtKHTxt.setText(khachHangTbl.getValueAt(selectedRow, 2) + "");
        ngayTaoTxt.setText(khachHangTbl.getValueAt(selectedRow,3)+"");
        trangThaiCB.setSelectedItem(khachHangTbl.getValueAt(selectedRow, 4));
    }
    
    void clearForm() {
        LocalDateTime ldt = LocalDateTime.now();
        String dateNow = (DateTimeFormatter.ofPattern("MM-dd-yyyy", Locale.ENGLISH).format(ldt));
        ngayTaoTxt.setText(dateNow);
        tenKHTxt.setText("");
        sdtKHTxt.setText("");
        trangThaiCB.setSelectedIndex(0);
       themBtn.setEnabled(true);
    }
    
    void validateKH(int choice) {
        String tenKH;
        String soDienThoai;
        int trangThai;
        LocalDateTime ldt = LocalDateTime.now();
        String dateNow = (DateTimeFormatter.ofPattern("MM-dd-yyyy", Locale.ENGLISH).format(ldt));
        Date now = new Date();
        Date ngayTao = now ;
        Date ngayCapNhat = now;
        tenKH = tenKHTxt.getText();
        
        if(tenKH.isEmpty() || tenKH.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên khách hàng");
            return;
        }
        soDienThoai = sdtKHTxt.getText();
        if(soDienThoai.isEmpty() || soDienThoai.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại");
            return;
        }
        if (soDienThoai.matches("[0-9]")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại chỉ chứa số");
            return;
        }
        if(!(soDienThoai.length()== 10)) {
            JOptionPane.showMessageDialog(this, "số điện thoại phải đủ 10 số");
            return;
        }
        if(trangThaiCB.getSelectedIndex() == 0) {
            trangThai = 1;
        } else {
            trangThai = 0;
        }
        if(choice == 1) {
            insertKH(tenKH, soDienThoai, ngayTao, ngayCapNhat, trangThai);
            statusPage();
        } else {
            int maTTKH;
            int selectedRow = khachHangTbl.getSelectedRow();
            maTTKH = (int) khachHangTbl.getValueAt(selectedRow, 0);
            updateKH(maTTKH, tenKH, soDienThoai, ngayTao, ngayCapNhat, trangThai);
            statusPage();
        }
        
        
    }
    void insertKH (String tenKH, String sDT, Date ngayTao, Date ngayCN, int trangThai) {
        String query = "insert into THONG_TIN_KH(TenKH, SDT, NgayTao, NgayCN, TrangThai)\n" +
                        "values (?, ?, ?,?, ?)";
        try {
            java.sql.Date  ngayTaoMoi = new java.sql.Date(ngayTao.getTime()); 
            java.sql.Date  ngayCapNhat = new java.sql.Date(ngayCN.getTime());
            Connection conn = DBconnect.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, tenKH);
            pstmt.setString(2, sDT);
            pstmt.setDate(3, ngayTaoMoi);
            pstmt.setDate(4, ngayCapNhat);
            pstmt.setInt(5, trangThai);
            pstmt.execute();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            statusPage();
            loadData(pageSelect);
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }
    void updateKH (int maTTKH,String tenKH, String sDT, Date ngayTao, Date ngayCN, int trangThai) {
        String query = "update THONG_TIN_KH\n" +
                        "set TenKH = ?, SDT = ?, NgayCN = ?, TrangThai = ?\n" +
                        "where MaTTKH = ?";
        try {
            java.sql.Date  ngayTaoMoi = new java.sql.Date(ngayTao.getTime()); 
            java.sql.Date  ngayCapNhat = new java.sql.Date(ngayCN.getTime());
            Connection conn = DBconnect.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, tenKH);
            pstmt.setString(2, sDT);
            pstmt.setDate(3, ngayCapNhat);
            pstmt.setInt(4, trangThai);
            pstmt.setInt(5, maTTKH);
            pstmt.execute();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            statusPage();
            loadData(pageSelect);
        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
        }
    }
    
    
    
    void loadData(int pageSelect) {
        DefaultTableModel model = (DefaultTableModel) khachHangTbl.getModel();
        model.setRowCount(0);
        String trangThai = null;
        String query = "select * from THONG_TIN_KH\n" +
                        "order by MaTTKH\n" +
                        "offset ? row\n" +
                        "fetch next 5 ROWS ONLY";;
        try {
            Connection conn = DBconnect.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, pageSelect);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {  
                if(rs.getInt("TrangThai") == 1) {
                    trangThai = "Hoạt động";
                } else {
                    trangThai = "Không hoạt động";
                }
                Object[] data = {
                  rs.getInt("MaTTKH"),
                  rs.getString("tenKH"), 
                  rs.getString("SDT"), 
                  rs.getDate("NgayTao"), 
                  trangThai
                };
                model.addRow(data);
            }
        } catch (SQLException e) {
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(khachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(khachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(khachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(khachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                khachHangJDialog dialog = new khachHangJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable khachHangTbl;
    private com.hyperbeast.swing.TextField ngayTaoTxt;
    private javax.swing.JLabel pageLbl;
    private com.hyperbeast.swing.TextField sdtKHTxt;
    private com.hyperbeast.swing.TextField tenKHTxt;
    private javax.swing.JButton themBtn;
    private com.hyperbeast.swing.Combobox trangThaiCB;
    // End of variables declaration//GEN-END:variables
}
