/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hyperbeast.form;

import com.hyperbeast.entity.KhuyenMai;
import com.hyperbeast.model.khuyenMaiModel;
import com.hyperbeast.utils.XacThuc;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class quanLyKM extends javax.swing.JPanel {

    /**
     * Creates new form khuyenMai
     */
    khuyenMaiModel kMModel = new khuyenMaiModel();
    Random generator = new Random();
    public quanLyKM() {
        initComponents();
        fillKhuyenMaiTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //DÙNG ĐỂ TEST_ASM
    public boolean validateKhuyenMaiTest(int choice, int maKM,String tenKhuyenMai, Date ngayBD, Date ngayKT, String maApDung, float mucGiam, int donVi, int trangThai) {
        Date now = new Date();
        
        ArrayList<KhuyenMai> listKM = kMModel.getKhuyenMai();
        if(tenKhuyenMai.isEmpty() || tenKhuyenMai.trim().isEmpty()) {
            throw new NullPointerException("tên khuyến mại rỗng");
        }
        ngayBD = ngayBatDauTxt.getDate();
        if(ngayBD == null) {
            throw new NullPointerException("nhập ngày bắt đầu rỗng");
        }
        ngayKT = ngayKetThucTxt.getDate();
        if(ngayKT == null) {
            throw new NullPointerException("ngày kết thúc rỗng");
        }
        if(trangThai != 1 || trangThai != 2) {
            throw new IllegalArgumentException("Trạng thái không hợp lệ");
        }
        
        if(!ngayKT.after(ngayBD)) {
            throw new IllegalArgumentException("Ngày kết thúc nhỏ hơn ngày bắt đầu");
        } 
        try {
            if(mucGiam <= 0 ) {
                throw new IllegalArgumentException("Mức giảm nhỏ hơn 0");
            }
            if(donVi == 1 && mucGiam > 100) {
                throw new IllegalArgumentException("Mức giảm % lớn hơn 100");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mức giảm phải nhập số");
            return false;
        }
        if(maApDung.isEmpty() || maApDung.trim().isEmpty()) {
            throw new NullPointerException("mã áp dụng rỗng");
        } else if(!(maApDung.length() == 8)) {
            throw new IllegalArgumentException("Mã áp dụng không đủ 8 ký tự");
        }
        
        if(choice == 1) {
            java.sql.Date  ngayBatDau = new java.sql.Date(ngayBD.getTime()); 
            java.sql.Date  ngayKetThuc = new java.sql.Date(ngayKT.getTime()); 
            for (KhuyenMai km : listKM) {
                if(km.getTenKhuyenMai().equals(tenKhuyenMai) || km.getMaApDung().equals(maApDung)) {
                    throw new IllegalArgumentException("Khuyến mại đã tồn tại");
                }
            }
            boolean check = kMModel.insertKhuyenMai(tenKhuyenMai, ngayBatDau, ngayKetThuc, mucGiam, maApDung, trangThai, donVi);
            if(!check) {
                return false;
            } else {
                return true;
            }
        } else if(choice == 2){
            java.sql.Date  ngayBatDau = new java.sql.Date(ngayBD.getTime()); 
            java.sql.Date  ngayKetThuc = new java.sql.Date(ngayKT.getTime()); 
            for (KhuyenMai km : listKM) {
                if(!(maKM == km.getMaKH())) {
                    throw new IllegalArgumentException("Khuyến mại không tồn tại");
                }
            }
            boolean check = kMModel.updateKhuyenMai(maKM, tenKhuyenMai, ngayBatDau, ngayKetThuc, mucGiam, maApDung, trangThai, donVi);
            if(!check) {
                 return false;
            } else {
                return true;
            }
        } else {
            throw new IllegalArgumentException("sai lựa chọn");
        }
    }
    //DÙNG ĐỂ TEST_ASM
    
    
    // tự động tạo mã áp dụng
    void taoMaApDung () {
        String alpha = "abcdefghijklmnopqrstuvwxyz";
        String alphaUpperCase = alpha.toUpperCase();
        String digits = "0123456789";
        String ALPHA_NUMERIC = alpha + alphaUpperCase + digits;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 8; i++) {
            int number = randomNumber(0, ALPHA_NUMERIC.length() - 1);
            char ch = ALPHA_NUMERIC.charAt(number);
            sb.append(ch);
        }
        maAPDungTxt.setText(sb.toString());
    }
    int randomNumber(int min, int max) {
            return generator.nextInt((max - min) + 1) + min;
    }
    // tự động tạo mã áp dụng
    
    
    void clearForm() {
        tenKhuyenMaiTxt.setText("");
        ngayBatDauTxt.setDate(null);
        ngayKetThucTxt.setDate(null);
        mucGiamGiaTxt.setText("");
        maAPDungTxt.setText("");
        vNDRB.setSelected(true);
        trangThaiCB.setSelectedIndex(0);
        luuBtn.setEnabled(true);
    } 
    
    
    
    void validateKhuyenMai(int choice) {
        String tenKhuyenMai;
        Date ngayBD;
        Date ngayKT;
        Date now = new Date();
        tenKhuyenMai = tenKhuyenMaiTxt.getText();
        float mucGiam;
        String maApDung;
        int donVi;
        int trangThai;
        int maKM;
        
        ArrayList<KhuyenMai> listKM = kMModel.getKhuyenMai();
        if(tenKhuyenMai.isEmpty() || tenKhuyenMai.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên khuyến mãi");
            return;
        }
        ngayBD = ngayBatDauTxt.getDate();
        if(ngayBD == null) {
            JOptionPane.showMessageDialog(this, "Chưa chọn ngày bắt đầu");
            return;
        }
        ngayKT = ngayKetThucTxt.getDate();
        if(ngayKT == null) {
            JOptionPane.showMessageDialog(this, "Chưa chọn ngày kết thúc");
            return;
        }
        
        if(!ngayKT.after(ngayBD)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải lớn hơn ngày bắt đầu");
            return;
        } 
        if(ngayKT.after(now)) {
            trangThaiCB.setSelectedIndex(0);
        } else {
            trangThaiCB.setSelectedIndex(1);
        }
        
        
        if(vNDRB.isSelected()) {
            donVi = 0;
        } else {
            donVi = 1;
        }
        try {
            mucGiam = Float.parseFloat(mucGiamGiaTxt.getText());
            if(mucGiam <= 0 ) {
                JOptionPane.showMessageDialog(this, "Mức giảm phải lớn hơn 0");
                return;
            }
            if(donVi == 1 && mucGiam > 100) {
                JOptionPane.showMessageDialog(this,"Phần trăm giảm phải nhỏ hơn hoặc bằng 100%");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mức giảm phải nhập số");
            return;
        }
        maApDung = maAPDungTxt.getText();
        if(maApDung.isEmpty() || maApDung.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã áp dụng");
            return;
        } else if(!(maApDung.length() == 8)) {
            JOptionPane.showMessageDialog(this, "Mã áp dụng phải có đủ 8 ký tự");
            return;
        }
        if(trangThaiCB.getSelectedIndex() == 0) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }
        
        if(choice == 1) {
            java.sql.Date  ngayBatDau = new java.sql.Date(ngayBD.getTime()); 
            java.sql.Date  ngayKetThuc = new java.sql.Date(ngayKT.getTime()); 
            for (KhuyenMai km : listKM) {
                if(km.getTenKhuyenMai().equals(tenKhuyenMai) || km.getMaApDung().equals(maApDung)) {
                    JOptionPane.showMessageDialog(this, "Khuyến mãi đã tồn tại");
                    return;
                }
            }
            boolean check = kMModel.insertKhuyenMai(tenKhuyenMai, ngayBatDau, ngayKetThuc, mucGiam, maApDung, trangThai, donVi);
            if(!check) {
                JOptionPane.showMessageDialog(this, "Lưu thất bại");
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Lưu thành công");
                fillKhuyenMaiTbl();
            }
        } else {
            java.sql.Date  ngayBatDau = new java.sql.Date(ngayBD.getTime()); 
            java.sql.Date  ngayKetThuc = new java.sql.Date(ngayKT.getTime()); 
            int selectedRow = khuyenMaiTbl.getSelectedRow();
            maKM = (int) khuyenMaiTbl.getValueAt(selectedRow, 0);
            boolean check = kMModel.updateKhuyenMai(maKM, tenKhuyenMai, ngayBatDau, ngayKetThuc, mucGiam, maApDung, trangThai, donVi);
            if(!check) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                fillKhuyenMaiTbl();
            }
        }
    }
    
    void getDataRow() {
        int selectedRow = khuyenMaiTbl.getSelectedRow();
        if(selectedRow < 0) {
            return;
        }
        titelLBl.setText("Thông tin khuyến mãi - " + khuyenMaiTbl.getValueAt(selectedRow, 0));
        Date ngayBD = (Date) khuyenMaiTbl.getValueAt(selectedRow, 2);
        Date ngayKT = (Date) khuyenMaiTbl.getValueAt(selectedRow, 3);
        tenKhuyenMaiTxt.setText("" +khuyenMaiTbl.getValueAt(selectedRow, 1));
        ngayBatDauTxt.setDate(ngayBD);
        ngayKetThucTxt.setDate(ngayKT);
        mucGiamGiaTxt.setText("" +khuyenMaiTbl.getValueAt(selectedRow, 4));
        if(khuyenMaiTbl.getValueAt(selectedRow, 5).equals("VNĐ")) {
            vNDRB.setSelected(true);
        } else {
            phanTramRB.setSelected(true);
        }
        maAPDungTxt.setText("" +khuyenMaiTbl.getValueAt(selectedRow, 6));
        trangThaiCB.setSelectedItem(khuyenMaiTbl.getValueAt(selectedRow, 7));
    }
    
    void fillKhuyenMaiTbl() {
        ArrayList<KhuyenMai> listKM = new ArrayList<>();
        listKM = kMModel.getKhuyenMai();
        DefaultTableModel model = (DefaultTableModel) khuyenMaiTbl.getModel();
        model.setRowCount(0);
        for (KhuyenMai kM : listKM) {
            Object[] data = {
                kM.getMaKH(), kM.getTenKhuyenMai(), kM.getNgayBatDau(), kM.getNgayKetThuc(), kM.getMucGiam(),
                kM.getDonVi(), kM.getMaApDung(), kM.getTrangThai()
            };
            model.addRow(data);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new com.hyperbeast.swing.PanelBorder();
        titelLBl = new javax.swing.JLabel();
        tenKhuyenMaiTxt = new com.hyperbeast.swing.TextField();
        mucGiamGiaTxt = new com.hyperbeast.swing.TextField();
        vNDRB = new com.hyperbeast.swing.RadioButtonCustom();
        phanTramRB = new com.hyperbeast.swing.RadioButtonCustom();
        maAPDungTxt = new com.hyperbeast.swing.TextField();
        trangThaiCB = new com.hyperbeast.swing.Combobox();
        luuBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ngayBatDauTxt = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ngayKetThucTxt = new com.toedter.calendar.JDateChooser();
        panelBorder2 = new com.hyperbeast.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        khuyenMaiTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        titelLBl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titelLBl.setForeground(new java.awt.Color(0, 102, 255));
        titelLBl.setText("Thông tin khuyến mãi");

        tenKhuyenMaiTxt.setLabelText("Tên khuyến mãi");

        mucGiamGiaTxt.setLabelText("Mức giảm giá");

        buttonGroup1.add(vNDRB);
        vNDRB.setSelected(true);
        vNDRB.setLabel("VNĐ");

        buttonGroup1.add(phanTramRB);
        phanTramRB.setLabel("%");

        maAPDungTxt.setLabelText("Mã áp dụng");

        trangThaiCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đang hoạt động", "Không hoạt động" }));
        trangThaiCB.setSelectedIndex(-1);
        trangThaiCB.setEnabled(false);
        trangThaiCB.setLabeText("Trạng thái");

        luuBtn.setBackground(new java.awt.Color(0, 102, 255));
        luuBtn.setForeground(new java.awt.Color(255, 255, 255));
        luuBtn.setText("Lưu");
        luuBtn.setEnabled(false);
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cập nhật");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Mới");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hyperbeast/icon/sale2.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hyperbeast/icon/exchange.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        ngayBatDauTxt.setDateFormatString("dd-MM-yyy");

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        ngayKetThucTxt.setDateFormatString("dd-MM-yyy");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titelLBl)
                        .addComponent(tenKhuyenMaiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(vNDRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(phanTramRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(mucGiamGiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ngayBatDauTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(ngayKetThucTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(maAPDungTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trangThaiCB, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titelLBl)
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(tenKhuyenMaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayBatDauTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayKetThucTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(mucGiamGiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vNDRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phanTramRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maAPDungTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(trangThaiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(luuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        khuyenMaiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc", "Mức giảm", "Đơn vị", "Mã áp dụng", "Trạng thái"
            }
        ));
        khuyenMaiTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khuyenMaiTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(khuyenMaiTbl);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Bảng khuyến mãi");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void khuyenMaiTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khuyenMaiTblMouseClicked
        // TODO add your handling code here:
        getDataRow();
        luuBtn.setEnabled(false);
    }//GEN-LAST:event_khuyenMaiTblMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       if(!XacThuc.isManager().equals("Quản lý")) {
            JOptionPane.showMessageDialog(this, "Tài khoản không có quyền thao tác");
            return;
        }
        clearForm();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        taoMaApDung();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        if(!XacThuc.isManager().equals("Quản lý")) {
            JOptionPane.showMessageDialog(this, "Tài khoản không có quyền thao tác");
            return;
        }
        validateKhuyenMai(1);
    }//GEN-LAST:event_luuBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!XacThuc.isManager().equals("Quản lý")) {
            JOptionPane.showMessageDialog(this, "Tài khoản không có quyền thao tác");
            return;
        }
        int selectedRow = khuyenMaiTbl.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "chưa chọn dòng cập nhật");
            return;
        }
        validateKhuyenMai(2);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable khuyenMaiTbl;
    private javax.swing.JButton luuBtn;
    private com.hyperbeast.swing.TextField maAPDungTxt;
    private com.hyperbeast.swing.TextField mucGiamGiaTxt;
    private com.toedter.calendar.JDateChooser ngayBatDauTxt;
    private com.toedter.calendar.JDateChooser ngayKetThucTxt;
    private com.hyperbeast.swing.PanelBorder panelBorder1;
    private com.hyperbeast.swing.PanelBorder panelBorder2;
    private com.hyperbeast.swing.RadioButtonCustom phanTramRB;
    private com.hyperbeast.swing.TextField tenKhuyenMaiTxt;
    private javax.swing.JLabel titelLBl;
    private com.hyperbeast.swing.Combobox trangThaiCB;
    private com.hyperbeast.swing.RadioButtonCustom vNDRB;
    // End of variables declaration//GEN-END:variables
}
