/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hyperbeast.form;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.hyperbeast.entity.HoaDon;
import com.hyperbeast.entity.HoaDonChiTiet;
import com.hyperbeast.entity.SanPham;
import com.hyperbeast.entity.SanPhamChiTiet;
import com.hyperbeast.model.hoaDonModel;
import com.hyperbeast.model.sanPhamModel;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class quanLyBanHang extends javax.swing.JPanel  {

    /**
     * Creates new form test
     */
    
    int pageNumberSPCT;
    int pageSPCT = 1;
    int pageSelectSPCT;
    hoaDonModel hDModel = new hoaDonModel();
    sanPhamModel sPModel = new sanPhamModel();
    ArrayList listSPCTSize;
    final JPanel jPanelCamera = new JPanel();
    public quanLyBanHang() {
        initComponents();
        hinhThucTTCB.setSelectedIndex(0);
        statusPageSPCT();
        getPageSPCT();
        fillSanPham();
        fillHoaDon();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//   void webCam () {
//        webCamPN.add(jPanelCamera);
//        Webcam webcam = Webcam.getDefault();
//        webcam.setViewSize(new Dimension(176, 144));
//
//        WebcamPanel webcamPanel = new WebcamPanel(webcam);
//        webcamPanel.setMirrored(true);
//
//        jPanelCamera.add(webcamPanel);
//        jPanelCamera.getParent().revalidate();
//    }
    
    
    void statusPageSPCT() {
        listSPCTSize = hDModel.getSizeCTSP();
        pageNumberSPCT = (int) Math.ceil((listSPCTSize.size()/5.0));
        pageLbl.setText(pageSPCT + "/" + pageNumberSPCT);
    }
    
    void getPageSPCT() {
        pageSelectSPCT = (pageSPCT - 1) * 5;
    }
    
    void getDataRowHoaDon(int rowSelected) {
        maHoaDonTxt.setText(hoaDonTbl.getValueAt(rowSelected, 0) + "");
        ngayTaoTxt.setText(hoaDonTbl.getValueAt(rowSelected, 1) +"");
        tenNhanVienTxt.setText(hoaDonTbl.getValueAt(rowSelected,2) +"");
    }
    
    void tinhTienThua() {
        int rowSelected = hoaDonTbl.getSelectedRow();
        if(rowSelected < 0) {
            return;
        }
        if(tienKhachDuaTxt.getText().isEmpty()) {
            tienThuaLbl.setText("");
            return;
        }
        
        int tongTien = tinhTongTien();
        int tienKhachDua;
        
        try {
            tienKhachDua = Integer.parseInt(tienKhachDuaTxt.getText());
            int tienThua = tienKhachDua - tongTien;
            if(tienThua < 0) {
                return;
            }
            String patternTienTe = "###,###,###";
            DecimalFormat formatTienTe = new DecimalFormat(patternTienTe);
            String stringTienTe= formatTienTe.format(tienThua);
            tienThuaLbl.setText(stringTienTe + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Chỉ Nhập số");
            tienKhachDuaTxt.setText("");
            tienThuaLbl.setText("");
        }
        
    }
    
    int tinhTongTien() {
        int rowSelected = hoaDonTbl.getSelectedRow();
        int maHD = (int) hoaDonTbl.getValueAt(rowSelected, 0);
        ArrayList<HoaDonChiTiet> listHDCT = hDModel.getHDCT(maHD);
        int tongTien = 0;
        for (HoaDonChiTiet hdct : listHDCT) {
            tongTien = (int) (tongTien + hdct.getThanhTien());
        }
        return tongTien;
    } 
    
    void addGioHang() {
        int rowSelectedHD = hoaDonTbl.getSelectedRow();
        int rowSelectedSP = sanPhamTbl.getSelectedRow();
        int maHD;
        int maCTSP;
        int soLuongThem;
        int soLuongSP;
        int soLuongCuoi;
        float donGia;
        float thanhTien;
        if(rowSelectedHD < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn thao tác");
            return;
        }
        maHD = (int) hoaDonTbl.getValueAt(rowSelectedHD, 0);
        maCTSP = (int) sanPhamTbl.getValueAt(rowSelectedSP, 0);
        soLuongSP = (int) sanPhamTbl.getValueAt(rowSelectedSP, 2);
        donGia = (float) sanPhamTbl.getValueAt(rowSelectedSP, 7);
        String check = JOptionPane.showInputDialog(this, "Nhập số lượng");
        if(check == null) {
            return;
        }
        System.out.println(check);
        try {
            soLuongThem = Integer.parseInt(check);
            if(soLuongThem <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
                return;
            }
            if(soLuongThem > soLuongSP) {
                JOptionPane.showMessageDialog(this, "Thất bại: vượt quá số lượng sản phẩm");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sai định dạng số lượng");
            return;
        }
        ArrayList<HoaDonChiTiet> listHDCT = hDModel.getHDCT(maHD);
        thanhTien = soLuongThem * donGia;
        soLuongCuoi = soLuongSP - soLuongThem;
        for (HoaDonChiTiet hdct : listHDCT) {
            if(hdct.getMaCTSP() == maCTSP) {
                int soLuongTrung = hdct.getSoLuong() + soLuongThem;
                float thanhTien2 = soLuongTrung * donGia;
                hDModel.updateHDCT(maHD, maCTSP, thanhTien2, soLuongTrung);
                fillGioHang(maHD);
                hDModel.updateCTSP(maCTSP, soLuongCuoi);
                fillSanPham();
                int tongTien = tinhTongTien();
                String patternTienTe = "###,###,###";
                DecimalFormat formatTienTe = new DecimalFormat(patternTienTe);
                String stringTienTe= formatTienTe.format(tongTien);
                tongTienLbl2.setText(stringTienTe);
                return;
            }
        }
        hDModel.insertHDCT(maCTSP, maHD, soLuongThem, thanhTien);
        fillGioHang(maHD);
        hDModel.updateCTSP(maCTSP, soLuongCuoi);
        fillSanPham();
        int tongTien = tinhTongTien();
        String patternTienTe = "###,###,###";
        DecimalFormat formatTienTe = new DecimalFormat(patternTienTe);
        String stringTienTe= formatTienTe.format(tongTien);
        tongTienLbl2.setText(stringTienTe);
    }
    
    void fillSanPham() {
        ArrayList<SanPhamChiTiet> listSPCT = hDModel.getSanPhamCT(pageSelectSPCT);
        DefaultTableModel model = (DefaultTableModel) sanPhamTbl.getModel();
        model.setRowCount(0);
        for (SanPhamChiTiet spct : listSPCT) {
            Object[] data = {
                spct.getMaCTSP(), spct.getTenSP(), spct.getSoLuong(), spct.getTenMau(),spct.getKichThuoc(),
                spct.getTenChatLieu(), spct.getTenChatLieuDe(), spct.getDonGia()
            };
            model.addRow(data);
        }
    }
    
    void fillGioHang(int maHD) {
        ArrayList<HoaDonChiTiet> listHDCT = hDModel.getHDCT(maHD);
        DefaultTableModel model = (DefaultTableModel) gioHangTbl.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet hdct : listHDCT) {
            Object[] data = {
                hdct.getMaCTSP(), hdct.getTenSanPham(), hdct.getSoLuong(), hdct.getDonGia(),
                hdct.getThanhTien()
            };
            model.addRow(data);
        }
    }
    
    void insertHoaDonCho () {
        LocalDateTime ldt = LocalDateTime.now();
        String dateNow = (DateTimeFormatter.ofPattern("MM-dd-yyyy", Locale.ENGLISH).format(ldt));
        String ngayTao = dateNow;
        String ngayCapNhat = dateNow;
        String trangThai = "Chờ thanh toán";
        int maTaiKhoan = 8;
        boolean check = hDModel.insertHoaDonCho(ngayTao, ngayCapNhat, trangThai, maTaiKhoan);
        if(check == true) {
            JOptionPane.showMessageDialog(this, "Tạo hóa đơn mới thành công");
            fillHoaDon();
        } else {
            JOptionPane.showMessageDialog(this, "Tạo hóa đơn mới thất bại");
            return;
        }
    }
    
    void updateHoaDon(String trangThai) {
        LocalDateTime ldt = LocalDateTime.now();
        String dateNow = (DateTimeFormatter.ofPattern("MM-dd-yyyy", Locale.ENGLISH).format(ldt));
        String ngayCapNhat = dateNow;
        int rowSelected = hoaDonTbl.getSelectedRow();
        if(rowSelected < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn thao tác");
            return;
        }
        int maHD = (int) hoaDonTbl.getValueAt(rowSelected, 0);
        float tongTien = tinhTongTien();
        int maTKKH = 2;
        String hinhThucThanhToan = hinhThucTTCB.getSelectedItem().toString();
        int choice = JOptionPane.showConfirmDialog(this,"Xác nhận thanh toán hóa đơn", "HyperBeast", JOptionPane.YES_NO_OPTION);
        if(choice == 0) {
            hDModel.updateHoaDon(maHD, ngayCapNhat, trangThai, maTKKH, tongTien);
            hDModel.insertThanhToan(maHD, maTKKH, hinhThucThanhToan);
            fillHoaDon();
        }
    }
    
    void fillHoaDon () {
        ArrayList<HoaDon> listHoaDon = hDModel.getHoaDon();
        DefaultTableModel model = (DefaultTableModel) hoaDonTbl.getModel();
        model.setRowCount(0);
        for (HoaDon hd : listHoaDon) {
            Object[] data = {
                hd.getMaHoaDon(),hd.getNgayTao(), hd.getTenNhanVien(),hd.getTrangThai()
            };
            model.addRow(data);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        materialTabbed1 = new tabbed.MaterialTabbed();
        jPanel1 = new javax.swing.JPanel();
        panelBorder3 = new com.hyperbeast.swing.PanelBorder();
        jScrollPane4 = new javax.swing.JScrollPane();
        hoaDonTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        radioButtonCustom1 = new com.hyperbeast.swing.RadioButtonCustom();
        radioButtonCustom2 = new com.hyperbeast.swing.RadioButtonCustom();
        radioButtonCustom3 = new com.hyperbeast.swing.RadioButtonCustom();
        radioButtonCustom4 = new com.hyperbeast.swing.RadioButtonCustom();
        panelBorder1 = new com.hyperbeast.swing.PanelBorder();
        tenGioHnagLbl = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        gioHangTbl = new javax.swing.JTable();
        suaBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        panelBorder2 = new com.hyperbeast.swing.PanelBorder();
        jScrollPane5 = new javax.swing.JScrollPane();
        sanPhamTbl = new javax.swing.JTable();
        textField1 = new com.hyperbeast.swing.TextField();
        jLabel4 = new javax.swing.JLabel();
        combobox1 = new com.hyperbeast.swing.Combobox();
        combobox2 = new com.hyperbeast.swing.Combobox();
        combobox3 = new com.hyperbeast.swing.Combobox();
        combobox4 = new com.hyperbeast.swing.Combobox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pageLbl = new javax.swing.JLabel();
        tongTienLbl = new com.hyperbeast.swing.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        maHoaDonTxt = new com.hyperbeast.swing.TextField();
        ngayTaoTxt = new com.hyperbeast.swing.TextField();
        tenKhachHangTxt = new com.hyperbeast.swing.TextField();
        hinhThucTTCB = new com.hyperbeast.swing.Combobox();
        tienKhachDuaTxt = new com.hyperbeast.swing.TextField();
        thanhToanBtn = new javax.swing.JButton();
        huyHoaDonBtn = new javax.swing.JButton();
        tenNhanVienTxt = new com.hyperbeast.swing.TextField();
        testLbl = new javax.swing.JLabel();
        soDienThoaiTxt = new com.hyperbeast.swing.TextField();
        testLbl2 = new javax.swing.JLabel();
        tongTienLbl2 = new javax.swing.JLabel();
        tienThuaLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setForeground(new java.awt.Color(255, 255, 255));

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        hoaDonTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày Tạo", "Tên nhân viên", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hoaDonTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoaDonTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(hoaDonTbl);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Hóa đơn");

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tạo hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonCustom1);
        radioButtonCustom1.setSelected(true);
        radioButtonCustom1.setText("Tất cả");

        buttonGroup1.add(radioButtonCustom2);
        radioButtonCustom2.setText("Chờ thanh toán");

        buttonGroup1.add(radioButtonCustom3);
        radioButtonCustom3.setText("Đã thanh toán");

        buttonGroup1.add(radioButtonCustom4);
        radioButtonCustom4.setText("Đã hủy");

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioButtonCustom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButtonCustom2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(radioButtonCustom3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButtonCustom4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioButtonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tenGioHnagLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tenGioHnagLbl.setForeground(new java.awt.Color(0, 102, 255));
        tenGioHnagLbl.setText("Giỏ hàng");

        gioHangTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã CTSP", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane6.setViewportView(gioHangTbl);

        suaBtn.setBackground(new java.awt.Color(0, 102, 255));
        suaBtn.setForeground(new java.awt.Color(255, 255, 255));
        suaBtn.setText("Sửa");

        xoaBtn.setBackground(new java.awt.Color(0, 102, 255));
        xoaBtn.setForeground(new java.awt.Color(255, 255, 255));
        xoaBtn.setText("Xóa");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tenGioHnagLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suaBtn)
                            .addComponent(xoaBtn))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tenGioHnagLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(suaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        sanPhamTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CTSP", "Tên sản phẩm", "Số lượng", "Màu sắc", "Kích thước", "Chất liệu ", "Chất liệu đế", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sanPhamTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sanPhamTblMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(sanPhamTbl);

        textField1.setLabelText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Sản phẩm");

        combobox1.setLabeText("Màu sắc");

        combobox2.setLabeText("Kích thước");

        combobox3.setLabeText("Chất liệu");

        combobox4.setLabeText("Chất liệu đế");

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText(">>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        pageLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pageLbl.setText("Trang");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageLbl))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tongTienLbl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thông tin hóa đơn");

        maHoaDonTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        maHoaDonTxt.setEnabled(false);
        maHoaDonTxt.setLabelText("Mã hóa đơn");

        ngayTaoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ngayTaoTxt.setEnabled(false);
        ngayTaoTxt.setLabelText("Ngày tạo");

        tenKhachHangTxt.setText("Hoàng Anh");
        tenKhachHangTxt.setLabelText("Tên khách hàng");

        hinhThucTTCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trực tiếp", "Chuyển khoản" }));
        hinhThucTTCB.setSelectedIndex(-1);
        hinhThucTTCB.setLabeText("Hình thức thanh toán");
        hinhThucTTCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinhThucTTCBActionPerformed(evt);
            }
        });

        tienKhachDuaTxt.setForeground(new java.awt.Color(0, 0, 0));
        tienKhachDuaTxt.setLabelText("Tiền khách đưa");
        tienKhachDuaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tienKhachDuaTxtKeyReleased(evt);
            }
        });

        thanhToanBtn.setBackground(new java.awt.Color(0, 102, 255));
        thanhToanBtn.setForeground(new java.awt.Color(255, 255, 255));
        thanhToanBtn.setText("Thanh toán");
        thanhToanBtn.setEnabled(false);
        thanhToanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanBtnActionPerformed(evt);
            }
        });

        huyHoaDonBtn.setBackground(new java.awt.Color(0, 102, 255));
        huyHoaDonBtn.setForeground(new java.awt.Color(255, 255, 255));
        huyHoaDonBtn.setText(" Hủy hóa đơn");
        huyHoaDonBtn.setEnabled(false);

        tenNhanVienTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tenNhanVienTxt.setEnabled(false);
        tenNhanVienTxt.setLabelText("Tên nhân viên");

        testLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLbl.setForeground(new java.awt.Color(255, 0, 51));
        testLbl.setText("Tổng tiền :");

        soDienThoaiTxt.setText("0328343389");
        soDienThoaiTxt.setLabelText("Số điện thoại");

        testLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testLbl2.setForeground(new java.awt.Color(0, 0, 0));
        testLbl2.setText("Tiền thừa :");

        tongTienLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tongTienLbl2.setForeground(new java.awt.Color(255, 0, 51));

        tienThuaLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tienThuaLbl.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout tongTienLblLayout = new javax.swing.GroupLayout(tongTienLbl);
        tongTienLbl.setLayout(tongTienLblLayout);
        tongTienLblLayout.setHorizontalGroup(
            tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tongTienLblLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(maHoaDonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngayTaoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenKhachHangTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hinhThucTTCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tienKhachDuaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenNhanVienTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soDienThoaiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tongTienLblLayout.createSequentialGroup()
                        .addComponent(thanhToanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(huyHoaDonBtn))
                    .addGroup(tongTienLblLayout.createSequentialGroup()
                        .addComponent(testLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tongTienLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tongTienLblLayout.createSequentialGroup()
                        .addComponent(testLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tienThuaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tongTienLblLayout.setVerticalGroup(
            tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tongTienLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maHoaDonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngayTaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenNhanVienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tenKhachHangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(soDienThoaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tongTienLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hinhThucTTCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tienKhachDuaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tienThuaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tongTienLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thanhToanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyHoaDonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tongTienLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tongTienLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        materialTabbed1.addTab("Hóa đơn", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        materialTabbed1.addTab("Lịch sử hóa đơn", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(pageSPCT <= pageNumberSPCT) {
            if(pageSPCT == 1) {
                return;
            }
            pageSPCT--;
            getPageSPCT();
            statusPageSPCT();
            fillSanPham();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(pageSPCT >= 1 && pageSPCT < pageNumberSPCT) {
            pageSPCT++;
            getPageSPCT();
            statusPageSPCT();
            fillSanPham();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insertHoaDonCho();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hoaDonTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDonTblMouseClicked
        // TODO add your handling code here:
        int rowSelected = hoaDonTbl.getSelectedRow();
        getDataRowHoaDon(rowSelected);
        int maHD = (int) hoaDonTbl.getValueAt(rowSelected, 0);
        String maHoaDon = "" + hoaDonTbl.getValueAt(rowSelected, 0);
        String trangThai = "" + hoaDonTbl.getValueAt(rowSelected, 3);
        if(trangThai.equals("Chờ thanh toán")) {
            thanhToanBtn.setEnabled(true);
            huyHoaDonBtn.setEnabled(true);
            suaBtn.setEnabled(true);
            xoaBtn.setEnabled(true);
        } else {
            thanhToanBtn.setEnabled(false);
            huyHoaDonBtn.setEnabled(false);
            suaBtn.setEnabled(false);
            xoaBtn.setEnabled(false);
        }
        tenGioHnagLbl.setText("Giỏ hàng - Hóa đơn " + maHoaDon);
        fillGioHang(maHD);
        
        int tongTien = tinhTongTien();
        String patternTienTe = "###,###,###";
        DecimalFormat formatTienTe = new DecimalFormat(patternTienTe);
        String stringTienTe= formatTienTe.format(tongTien);
        tongTienLbl2.setText(stringTienTe);
    }//GEN-LAST:event_hoaDonTblMouseClicked

    private void sanPhamTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanPhamTblMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2) {
            int rowSelected = hoaDonTbl.getSelectedRow();
            String trangThai = "" + hoaDonTbl.getValueAt(rowSelected, 3);
            if(trangThai.equals("Đã thanh toán")) {
                return;
            }
            addGioHang();
        }
    }//GEN-LAST:event_sanPhamTblMousePressed

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here:
        int rowSelectedHD = hoaDonTbl.getSelectedRow();
        int maHD = (int) hoaDonTbl.getValueAt(rowSelectedHD, 0);
        ArrayList<HoaDonChiTiet> listHDCT = hDModel.getHDCT(maHD);
        int rowSelectedGH = gioHangTbl.getSelectedRow();
        int maCTSP = (int) gioHangTbl.getValueAt(rowSelectedGH, 0);
        int soLuongXoa = (int) gioHangTbl.getValueAt(rowSelectedGH, 2);
        int maHDCT = listHDCT.get(rowSelectedGH).getMaHDCT();
        int choice = JOptionPane.showConfirmDialog(this,"Xác nhận xóa khỏi giỏ hàng", "HyperBeast", JOptionPane.YES_NO_OPTION);
        if(choice == 0) {
            hDModel.deleteHDCT(maHDCT);
            int soLuongSP = sPModel.getSoluongCTSP(maCTSP);
            int soLuongCuoi = soLuongXoa + soLuongSP;
            fillGioHang(maHD);
            hDModel.updateCTSP(maCTSP, soLuongCuoi);
            fillSanPham();
            int tongTien = tinhTongTien();
            String patternTienTe = "###,###,###";
            DecimalFormat formatTienTe = new DecimalFormat(patternTienTe);
            String stringTienTe= formatTienTe.format(tongTien);
            tongTienLbl2.setText(stringTienTe);
        }
    }//GEN-LAST:event_xoaBtnActionPerformed

    private void tienKhachDuaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tienKhachDuaTxtKeyReleased
        // TODO add your handling code here:
        tinhTienThua();
        
    }//GEN-LAST:event_tienKhachDuaTxtKeyReleased

    private void hinhThucTTCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinhThucTTCBActionPerformed
        // TODO add your handling code here:
        int rowSelected = hoaDonTbl.getSelectedRow();
        if(rowSelected < 0) {
            return;
        }
        if(hinhThucTTCB.getSelectedIndex() == 1) {
            int tongTien = tinhTongTien();
            tienKhachDuaTxt.setEnabled(false);
            tienKhachDuaTxt.setText(tongTien + "");
            tinhTienThua();
        } else {
            tienKhachDuaTxt.setEnabled(true);
        }
    }//GEN-LAST:event_hinhThucTTCBActionPerformed

    private void thanhToanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanBtnActionPerformed
        // TODO add your handling code here:
        updateHoaDon("Đã thanh toán");
    }//GEN-LAST:event_thanhToanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.hyperbeast.swing.Combobox combobox1;
    private com.hyperbeast.swing.Combobox combobox2;
    private com.hyperbeast.swing.Combobox combobox3;
    private com.hyperbeast.swing.Combobox combobox4;
    private javax.swing.JTable gioHangTbl;
    private com.hyperbeast.swing.Combobox hinhThucTTCB;
    private javax.swing.JTable hoaDonTbl;
    private javax.swing.JButton huyHoaDonBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private com.hyperbeast.swing.TextField maHoaDonTxt;
    private tabbed.MaterialTabbed materialTabbed1;
    private com.hyperbeast.swing.TextField ngayTaoTxt;
    private javax.swing.JLabel pageLbl;
    private com.hyperbeast.swing.PanelBorder panelBorder1;
    private com.hyperbeast.swing.PanelBorder panelBorder2;
    private com.hyperbeast.swing.PanelBorder panelBorder3;
    private com.hyperbeast.swing.RadioButtonCustom radioButtonCustom1;
    private com.hyperbeast.swing.RadioButtonCustom radioButtonCustom2;
    private com.hyperbeast.swing.RadioButtonCustom radioButtonCustom3;
    private com.hyperbeast.swing.RadioButtonCustom radioButtonCustom4;
    private javax.swing.JTable sanPhamTbl;
    private com.hyperbeast.swing.TextField soDienThoaiTxt;
    private javax.swing.JButton suaBtn;
    private javax.swing.JLabel tenGioHnagLbl;
    private com.hyperbeast.swing.TextField tenKhachHangTxt;
    private com.hyperbeast.swing.TextField tenNhanVienTxt;
    private javax.swing.JLabel testLbl;
    private javax.swing.JLabel testLbl2;
    private com.hyperbeast.swing.TextField textField1;
    private javax.swing.JButton thanhToanBtn;
    private com.hyperbeast.swing.TextField tienKhachDuaTxt;
    private javax.swing.JLabel tienThuaLbl;
    private com.hyperbeast.swing.PanelBorder tongTienLbl;
    private javax.swing.JLabel tongTienLbl2;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
